on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to Roblox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup rokit
        run: |
          curl -sSf https://raw.githubusercontent.com/rojo-rbx/rokit/main/scripts/install.sh | bash
          ~/.rokit/bin/rokit install --no-trust-check

      - name: Install packages
        run: ~/.rokit/bin/wally install

      - name: Build
        uses: CompeyDev/rojo-build-action@0.1.5
        with:
          output: build

      - name: Upload
        uses: Ulferno/upload-to-roblox@v1.0.4
        with:
          api-key: ${{ secrets.ROBLOX_API }}
          universeId: ${{ secrets.ROBLOX_UNIVERSE }}
          placeId: ${{ secrets.ROBLOX_PLACE }}
          file: build.rbxlx
